### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by dhulihan** [cloudspannerecosystem/yo#111]
It would be nice to have a hosted `yo` docker image available for repeatable changes. 

Example use case: I could add a `make yo` to my Makefile that generates code with a specific version of `yo`, and then commit that to my project, so all collaborators are generating code with the same version of `yo`.

side note: [sqlc](https://github.com/kyleconroy/sqlc) (a popular sql code generator) has a [docker image](https://hub.docker.com/r/kjconroy/sqlc) available.

**Comment by a-millert** [comment]
@dhulihan Why not use [tools.go](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module) to version and install `yo` in the CI workflow and use it via a make command?

**Comment by dhulihan** [comment]
@a-millert good call, we can also use `go run` and specify a version as well:

```sh
go run go.mercari.io/yo@v0.5.4
```
