### ISSUE TITLE
COLUMN_DEFAULT is not found in spanner 

### ISSUE THREAD

**Issue by Jian11-Liu** [cloudspannerecosystem/yo#39]
Hello.

when I use yo by command line, I got a error like this:

```
$ yo pj-name instance-name db-name
error: spanner: code = "InvalidArgument", desc = "Name COLUMN_DEFAULT not found inside c [at 1:45]\nSELECT c.COLUMN_NAME, c.ORDINAL_POSITION, c.COLUMN_DEFAULT, c.IS_NULLABLE, c....\n  

```
then I send a query on spanner:

```
spanner> SELECT * from INFORMATION_SCHEMA.COLUMNS;
+---------------+--------------+----------------+--------------------------+------------------+-------------+--------------+
| TABLE_CATALOG | TABLE_SCHEMA | TABLE_NAME     | COLUMN_NAME              | ORDINAL_POSITION | IS_NULLABLE | SPANNER_TYPE |
+---------------+--------------+----------------+--------------------------+------------------+-------------+--------------+
```

It's seems there is no 'COLUMN_DEFAULT ' in INFORMATION_SCHEMA.

refenrence the source code:
https://github.com/cloudspannerecosystem/yo/blob/master/loaders/spanner.go#L231
```
	const sqlstr = `SELECT ` +
		`c.COLUMN_NAME, c.ORDINAL_POSITION, c.COLUMN_DEFAULT, c.IS_NULLABLE, c.SPANNER_TYPE, ` +
		`EXISTS (` +
		`  SELECT 1 FROM INFORMATION_SCHEMA.INDEX_COLUMNS ic ` +
		`  WHERE ic.TABLE_SCHEMA = "" and ic.TABLE_NAME = c.TABLE_NAME ` +
		`  AND ic.COLUMN_NAME = c.COLUMN_NAME` +
		`  AND ic.INDEX_NAME = "PRIMARY_KEY" ` +
		`) IS_PRIMARY_KEY ` +
		`FROM INFORMATION_SCHEMA.COLUMNS c ` +
		`WHERE c.TABLE_SCHEMA = "" AND c.TABLE_NAME = @table ` +
		`ORDER BY c.ORDINAL_POSITION`
```

**Comment by kazegusuri** [comment]
hmm... I tried the query in several instances including very old and newly created but they all have `COLUMN_DEFAULT` column. Do you use actual instance or some kind of emulator?

**Comment by kazegusuri** [comment]
I found the official spanner emulator does not support COLUMN_DEFAULT.

**Comment by Jian11-Liu** [comment]
> hmm... I tried the query in several instances including very old and newly created but they all have `COLUMN_DEFAULT` column. Do you use actual instance or some kind of emulator?

Thanks for your response rapidly.
Maybe my spanner is too old.

```
C:\Users\jpyou\go\bin>gcloud version
Google Cloud SDK 290.0.1
beta 2019.05.17
bq 2.0.56
core 2020.04.24
gsutil 4.49
```

**I have another issue.**
I use windows 10 pro, when I download yo again and run yo ,
I got the same error message as before.

`error: spanner: code = "InvalidArgument", desc = "Name COLUMN_DEFAULT not found inside c [at 1:45]\nSELECT c.COLUMN_NAME, c.ORDINAL_POSITION, c.COLUMN_DEFAULT, c.IS_NULLABLE, c....\n`

**Comment by kazegusuri** [comment]
I guess you use the tagged version of yo. The change is not tagged yet. If you try please use master branch by `go get go.mercari.io/yo@master`.

**Comment by Jian11-Liu** [comment]
> I guess you use the tagged version of yo. The change is not tagged yet. If you try please use master branch by `go get go.mercari.io/yo@master`.

Thanks for your reply in holiday.

I tried get the yo.exe from master branch.
I got another message when I run the yo.exe,

```
yo pj-name instance-name db-name
error: exit status 2
```

**Comment by Jian11-Liu** [comment]
> ```
> yo pj-name instance-name db-name
> error: exit status 2
> ```

I build the yo again and solved this problem, thank you.
