### ISSUE TITLE
Probably multi-STORING-column Index's FuncName is not stable

### ISSUE THREAD

**Issue by uechoco** [cloudspannerecosystem/yo#93]
For example:

There is an index:
`CREATE INDEX IndexNameA ON TableA(ColumnC, ColumnB, ColumnA) STORING (ColumnE, ColumnD);`

In some teammates environment, yo-bin generates `FindTableAByColumnDColumnEColumnCColumnBColumnA`
However, in another teammate environment, yo-bin generates `FindTableAByColumnEColumnDColumnCColumnBColumnA`, it switched STORING columns order.

I seem that [loaders.SpanIndesColumns()](https://github.com/cloudspannerecosystem/yo/blob/f04de876c09a8b5c7b0ed2296ea303934e78a741/loaders/spanner.go#L358) does not handle SOTRING columns' order.

```
+------------------+-------------+
| ORDINAL_POSITION | COLUMN_NAME |
+------------------+-------------+
| NULL             | ColumnE     |
| NULL             | ColumnD     |
| 1                | ColumnC     |
| 2                | ColumnB     |
| 3                | ColumnA     |
+------------------+-------------+
```

If this sql fix with `ORDER BY ORDINAL_POSITION, COLUMN_NAME`, the STORING columns' order may become stable.
Do you think whether this is a bug or a breaking change?

**Comment by kazegusuri** [comment]
Thank you for the report. I found the root problem for this.

There are 2 types of schema loaders in Yo, using DDL file parser and using spanner information schema.

The parser type determines the columns order by the DDL definition. For example,

```
CREATE INDEX Foo ON FooIndex(A, B) STORING(Z, Y);
```

The columns order is A, B then the storing columns order is Z, Y as described in the DDL. So the function name becomes `FooIndexZYAB`. 

While, in the loader with information schema, it uses the results of a query to [information schema](https://cloud.google.com/spanner/docs/information-schema#information_schemaindex_columns).  The table contains `ORDINAL_POSITION` that represents the order of normal columns but not contain the order information for storing columns (described by DDL). So the loader cannot restore the information of DDL perfectly. As the result, the loader just decides the order for storing columns as lexical order. So the loaders can generate different function names with single schema.

We need to ignore the order of DDL in parser loader and use lexical order always in both loaders to unify the generated function name. It will be breaking changes and ask users to fix the usage. So I think we cannot fix this issue by v1.

In v2, it changed the logic for the function name for index. So there is no issue like this. However v2 is not officially released.

Another workarounds are:

* Use single loader to generate code always
* Use own template to generate code for index functions

**Comment by uechoco** [comment]
Thank you for your explanation!
Surely, we used the loader with information-schema.
I understood that's why it's not stable.

I'm thinking that we will use the DDL file loader always.

Thank you.
